#!/bin/bash
# exclude from git with:
# git update-index --skip-worktree tests/steam_test_credentials
# revert:
# git update-index --no-skip-worktree tests/steam_test_credentials
#shellcheck disable=SC2034 # used elsewhere
steam_test_username=""
#shellcheck disable=SC2034 # used elsewhere
steam_test_password=""
