#!/bin/sh

set -o errexit
set -o nounset

GROUP_NAME="$USER_NAME"
if [ "$(id --user "$USER_ID" 2> /dev/null)" != "$USER_ID" ] || [ "$(id --group "$USER_ID" 2> /dev/null)" != "$GROUP_ID" ]; then
    echo "[info][setupUser] changing user id"
    old_user_id="$(id --user "$USER_NAME")"
    usermod -u "$USER_ID" "$USER_NAME"
    find /home/ -uid "$old_user_id" -exec chown "$USER_ID" "{}" \;

    echo "[info][setupUser] changing group id"
    old_group_id="$(id --group "$USER_NAME")"
    groupmod -g "$GROUP_ID" "$GROUP_NAME"
    find /home/ -gid "$old_group_id" -exec chown ":$GROUP_ID" "{}" \;
fi
